version: "3.8"

configs:
  prometheus_config:
    file: configs/prometheus.yml
  promtail_config:
    file: configs/promtail.yaml


volumes:
  grafana_config:
  prometheus_data:

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/data
    command:
      - "--config.file=/prometheus_config"
    ports:
      - 9090:9090
    configs:
      - prometheus_config

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml


  nginx_exporter:
    image: nginx-exporter
    ports:
      - 9113:9113
    command: -nginx.scrape-uri http://192.168.1.34:8888/metrics


  promtail:
    image: grafana/promtail
    volumes:
      - /var/log/nginx:/var/log
    command: -config.file=/promtail_config
    configs:
      - promtail_config


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_config:/var/lib/grafana
