version: '3.8'

volumes:
  nextcloud:
  db:

secrets:
  postgres_db:
    file: secrets/postgres_db
  postgres_user:
    file: secrets/postgres_user
  postgres_password:
    file: secrets/postgres_password
  nextcloud_user:
    file: secrets/nextcloud_user
  nextcloud_password:
    file: secrets/nextcloud_password

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_db
      - postgres_password


  app:
    image: nextcloud
    ports:
      - 8765:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_password
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_db
      - postgres_password
      - nextcloud_user
      - nextcloud_password
