global:
  scrape_interval: 20s

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node
    
    static_configs:
    - targets: ['192.168.1.34:9100']
